/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Hanken Grotesk"', 'sans-serif'],
        display: ['"Hanken Grotesk"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        "display-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "label-mono": ["JetBrains Mono"],
        "caption": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"]
      },
      colors: {
        "inverse-on-surface": "#2b3133",
        "on-primary-container": "#00424f",
        "inverse-surface": "#dee3e6",
        "on-primary-fixed": "#001f26",
        "surface-container": "#1b2122",
        "on-error": "#690005",
        "tertiary-container": "#e89337",
        "surface-dim": "#0e1416",
        "on-primary": "#003640",
        "surface-container-lowest": "#090f11",
        "on-secondary-fixed": "#00174b",
        "on-tertiary-fixed": "#2d1600",
        "on-secondary-fixed-variant": "#003ea8",
        "on-surface-variant": "#bcc9cd",
        "on-tertiary-container": "#5b3200",
        "surface-bright": "#343a3c",
        "surface-variant": "#303638",
        "surface-container-low": "#171d1e",
        "secondary-fixed": "#dbe1ff",
        "surface-container-high": "#252b2d",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004e5c",
        "primary": "#4cd7f6",
        "surface-container-highest": "#303638",
        "primary-fixed": "#acedff",
        "background": "#0e1416",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary-container": "#cdd7ff",
        "secondary-container": "#0053db",
        "secondary": "#b4c5ff",
        "primary-fixed-dim": "#4cd7f6",
        "inverse-primary": "#00687a",
        "tertiary-fixed-dim": "#ffb873",
        "outline-variant": "#3d494c",
        "primary-container": "#06b6d4",
        "tertiary-fixed": "#ffdcbf",
        "on-tertiary-fixed-variant": "#6a3b00",
        "surface-tint": "#4cd7f6",
        "surface": "#0e1416",
        "on-surface": "#dee3e6",
        "outline": "#869397",
        "on-tertiary": "#4b2800",
        "error": "#ffb4ab",
        "tertiary": "#ffb873",
        "on-background": "#dee3e6",
        "on-secondary": "#002a78",
        "error-container": "#93000a"
      },
      spacing: {
        "unit-xl": "32px",
        "container-margin": "24px",
        "unit-md": "16px",
        "gutter": "16px",
        "unit-sm": "8px",
        "section-gap": "48px",
        "unit-lg": "24px",
        "navbar-height": "64px",
        "unit-xs": "4px"
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-mono": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "caption": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
